export const RESOURCES = {
  transactions: '/immediate-transactions',
  scheduledReversibleTransactions: '/scheduled-reversible-transactions',
  executedReversibleTransactions: '/executed-reversible-transactions',
  cancelledReversibleTransactions: '/cancelled-reversible-transactions',
  accounts: '/accounts',
  blocks: '/blocks',
  minerRewards: '/miner-rewards',
  highSecuritySets: '/high-security-sets',
  errors: '/errors',
  wormhole: '/wormhole',
  multisigCreated: '/multisig-created',
  multisigProposalCreated: '/multisig-proposal-created',
  multisigSignerApproved: '/multisig-signer-approved',
  multisigProposalReady: '/multisig-proposal-ready',
  multisigProposalExecuted: '/multisig-proposal-executed',
  multisigProposalCancelled: '/multisig-proposal-cancelled',
  multisigProposalRemoved: '/multisig-proposal-removed',
  multisigDepositsClaimed: '/multisig-deposits-claimed'
} as const;
