/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as MultisigSignerApprovedIndexRouteImport } from './routes/multisig-signer-approved/index'
import { Route as MultisigProposalsIndexRouteImport } from './routes/multisig-proposals/index'
import { Route as MultisigProposalRemovedIndexRouteImport } from './routes/multisig-proposal-removed/index'
import { Route as MultisigProposalReadyIndexRouteImport } from './routes/multisig-proposal-ready/index'
import { Route as MultisigProposalExecutedIndexRouteImport } from './routes/multisig-proposal-executed/index'
import { Route as MultisigProposalCreatedIndexRouteImport } from './routes/multisig-proposal-created/index'
import { Route as MultisigProposalCancelledIndexRouteImport } from './routes/multisig-proposal-cancelled/index'
import { Route as MultisigDepositsClaimedIndexRouteImport } from './routes/multisig-deposits-claimed/index'
import { Route as MultisigCreatedIndexRouteImport } from './routes/multisig-created/index'
import { Route as MinerRewardsIndexRouteImport } from './routes/miner-rewards/index'
import { Route as MinerLeaderboardIndexRouteImport } from './routes/miner-leaderboard/index'
import { Route as HighSecuritySetsIndexRouteImport } from './routes/high-security-sets/index'
import { Route as ErrorsIndexRouteImport } from './routes/errors/index'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TransactionsHashRouteImport } from './routes/transactions/$hash'
import { Route as MultisigSignerApprovedHashRouteImport } from './routes/multisig-signer-approved/$hash'
import { Route as MultisigProposalsIdRouteImport } from './routes/multisig-proposals/$id'
import { Route as MultisigProposalRemovedHashRouteImport } from './routes/multisig-proposal-removed/$hash'
import { Route as MultisigProposalReadyHashRouteImport } from './routes/multisig-proposal-ready/$hash'
import { Route as MultisigProposalExecutedHashRouteImport } from './routes/multisig-proposal-executed/$hash'
import { Route as MultisigProposalCreatedHashRouteImport } from './routes/multisig-proposal-created/$hash'
import { Route as MultisigProposalCancelledHashRouteImport } from './routes/multisig-proposal-cancelled/$hash'
import { Route as MultisigDepositsClaimedHashRouteImport } from './routes/multisig-deposits-claimed/$hash'
import { Route as MultisigCreatedHashRouteImport } from './routes/multisig-created/$hash'
import { Route as MinerRewardsHashRouteImport } from './routes/miner-rewards/$hash'
import { Route as HighSecuritySetsHashRouteImport } from './routes/high-security-sets/$hash'
import { Route as ErrorsIdRouteImport } from './routes/errors/$id'
import { Route as BlocksIdRouteImport } from './routes/blocks/$id'
import { Route as AccountsIdRouteImport } from './routes/accounts/$id'
import { Route as DevGraphqlBenchmarkIndexRouteImport } from './routes/dev/graphql-benchmark/index'
import { Route as TransactionsWormholeIdRouteImport } from './routes/transactions/wormhole/$id'
import { Route as TransactionsScheduledReversibleTxIdRouteImport } from './routes/transactions/scheduled-reversible/$txId'
import { Route as TransactionsExecutedReversibleTxIdRouteImport } from './routes/transactions/executed-reversible/$txId'
import { Route as TransactionsCancelledReversibleTxIdRouteImport } from './routes/transactions/cancelled-reversible/$txId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigSignerApprovedIndexRoute =
  MultisigSignerApprovedIndexRouteImport.update({
    id: '/multisig-signer-approved/',
    path: '/multisig-signer-approved/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalsIndexRoute = MultisigProposalsIndexRouteImport.update({
  id: '/multisig-proposals/',
  path: '/multisig-proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigProposalRemovedIndexRoute =
  MultisigProposalRemovedIndexRouteImport.update({
    id: '/multisig-proposal-removed/',
    path: '/multisig-proposal-removed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalReadyIndexRoute =
  MultisigProposalReadyIndexRouteImport.update({
    id: '/multisig-proposal-ready/',
    path: '/multisig-proposal-ready/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalExecutedIndexRoute =
  MultisigProposalExecutedIndexRouteImport.update({
    id: '/multisig-proposal-executed/',
    path: '/multisig-proposal-executed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalCreatedIndexRoute =
  MultisigProposalCreatedIndexRouteImport.update({
    id: '/multisig-proposal-created/',
    path: '/multisig-proposal-created/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalCancelledIndexRoute =
  MultisigProposalCancelledIndexRouteImport.update({
    id: '/multisig-proposal-cancelled/',
    path: '/multisig-proposal-cancelled/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigDepositsClaimedIndexRoute =
  MultisigDepositsClaimedIndexRouteImport.update({
    id: '/multisig-deposits-claimed/',
    path: '/multisig-deposits-claimed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigCreatedIndexRoute = MultisigCreatedIndexRouteImport.update({
  id: '/multisig-created/',
  path: '/multisig-created/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinerRewardsIndexRoute = MinerRewardsIndexRouteImport.update({
  id: '/miner-rewards/',
  path: '/miner-rewards/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinerLeaderboardIndexRoute = MinerLeaderboardIndexRouteImport.update({
  id: '/miner-leaderboard/',
  path: '/miner-leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const HighSecuritySetsIndexRoute = HighSecuritySetsIndexRouteImport.update({
  id: '/high-security-sets/',
  path: '/high-security-sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIndexRoute = ErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsHashRoute = TransactionsHashRouteImport.update({
  id: '/transactions/$hash',
  path: '/transactions/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigSignerApprovedHashRoute =
  MultisigSignerApprovedHashRouteImport.update({
    id: '/multisig-signer-approved/$hash',
    path: '/multisig-signer-approved/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalsIdRoute = MultisigProposalsIdRouteImport.update({
  id: '/multisig-proposals/$id',
  path: '/multisig-proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigProposalRemovedHashRoute =
  MultisigProposalRemovedHashRouteImport.update({
    id: '/multisig-proposal-removed/$hash',
    path: '/multisig-proposal-removed/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalReadyHashRoute =
  MultisigProposalReadyHashRouteImport.update({
    id: '/multisig-proposal-ready/$hash',
    path: '/multisig-proposal-ready/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalExecutedHashRoute =
  MultisigProposalExecutedHashRouteImport.update({
    id: '/multisig-proposal-executed/$hash',
    path: '/multisig-proposal-executed/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalCreatedHashRoute =
  MultisigProposalCreatedHashRouteImport.update({
    id: '/multisig-proposal-created/$hash',
    path: '/multisig-proposal-created/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigProposalCancelledHashRoute =
  MultisigProposalCancelledHashRouteImport.update({
    id: '/multisig-proposal-cancelled/$hash',
    path: '/multisig-proposal-cancelled/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigDepositsClaimedHashRoute =
  MultisigDepositsClaimedHashRouteImport.update({
    id: '/multisig-deposits-claimed/$hash',
    path: '/multisig-deposits-claimed/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultisigCreatedHashRoute = MultisigCreatedHashRouteImport.update({
  id: '/multisig-created/$hash',
  path: '/multisig-created/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const MinerRewardsHashRoute = MinerRewardsHashRouteImport.update({
  id: '/miner-rewards/$hash',
  path: '/miner-rewards/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const HighSecuritySetsHashRoute = HighSecuritySetsHashRouteImport.update({
  id: '/high-security-sets/$hash',
  path: '/high-security-sets/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIdRoute = ErrorsIdRouteImport.update({
  id: '/errors/$id',
  path: '/errors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIdRoute = BlocksIdRouteImport.update({
  id: '/blocks/$id',
  path: '/blocks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGraphqlBenchmarkIndexRoute =
  DevGraphqlBenchmarkIndexRouteImport.update({
    id: '/dev/graphql-benchmark/',
    path: '/dev/graphql-benchmark/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsWormholeIdRoute = TransactionsWormholeIdRouteImport.update({
  id: '/transactions/wormhole/$id',
  path: '/transactions/wormhole/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsScheduledReversibleTxIdRoute =
  TransactionsScheduledReversibleTxIdRouteImport.update({
    id: '/transactions/scheduled-reversible/$txId',
    path: '/transactions/scheduled-reversible/$txId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsExecutedReversibleTxIdRoute =
  TransactionsExecutedReversibleTxIdRouteImport.update({
    id: '/transactions/executed-reversible/$txId',
    path: '/transactions/executed-reversible/$txId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsCancelledReversibleTxIdRoute =
  TransactionsCancelledReversibleTxIdRouteImport.update({
    id: '/transactions/cancelled-reversible/$txId',
    path: '/transactions/cancelled-reversible/$txId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blocks/$id': typeof BlocksIdRoute
  '/errors/$id': typeof ErrorsIdRoute
  '/high-security-sets/$hash': typeof HighSecuritySetsHashRoute
  '/miner-rewards/$hash': typeof MinerRewardsHashRoute
  '/multisig-created/$hash': typeof MultisigCreatedHashRoute
  '/multisig-deposits-claimed/$hash': typeof MultisigDepositsClaimedHashRoute
  '/multisig-proposal-cancelled/$hash': typeof MultisigProposalCancelledHashRoute
  '/multisig-proposal-created/$hash': typeof MultisigProposalCreatedHashRoute
  '/multisig-proposal-executed/$hash': typeof MultisigProposalExecutedHashRoute
  '/multisig-proposal-ready/$hash': typeof MultisigProposalReadyHashRoute
  '/multisig-proposal-removed/$hash': typeof MultisigProposalRemovedHashRoute
  '/multisig-proposals/$id': typeof MultisigProposalsIdRoute
  '/multisig-signer-approved/$hash': typeof MultisigSignerApprovedHashRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/accounts': typeof AccountsIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/errors': typeof ErrorsIndexRoute
  '/high-security-sets': typeof HighSecuritySetsIndexRoute
  '/miner-leaderboard': typeof MinerLeaderboardIndexRoute
  '/miner-rewards': typeof MinerRewardsIndexRoute
  '/multisig-created': typeof MultisigCreatedIndexRoute
  '/multisig-deposits-claimed': typeof MultisigDepositsClaimedIndexRoute
  '/multisig-proposal-cancelled': typeof MultisigProposalCancelledIndexRoute
  '/multisig-proposal-created': typeof MultisigProposalCreatedIndexRoute
  '/multisig-proposal-executed': typeof MultisigProposalExecutedIndexRoute
  '/multisig-proposal-ready': typeof MultisigProposalReadyIndexRoute
  '/multisig-proposal-removed': typeof MultisigProposalRemovedIndexRoute
  '/multisig-proposals': typeof MultisigProposalsIndexRoute
  '/multisig-signer-approved': typeof MultisigSignerApprovedIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/cancelled-reversible/$txId': typeof TransactionsCancelledReversibleTxIdRoute
  '/transactions/executed-reversible/$txId': typeof TransactionsExecutedReversibleTxIdRoute
  '/transactions/scheduled-reversible/$txId': typeof TransactionsScheduledReversibleTxIdRoute
  '/transactions/wormhole/$id': typeof TransactionsWormholeIdRoute
  '/dev/graphql-benchmark': typeof DevGraphqlBenchmarkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blocks/$id': typeof BlocksIdRoute
  '/errors/$id': typeof ErrorsIdRoute
  '/high-security-sets/$hash': typeof HighSecuritySetsHashRoute
  '/miner-rewards/$hash': typeof MinerRewardsHashRoute
  '/multisig-created/$hash': typeof MultisigCreatedHashRoute
  '/multisig-deposits-claimed/$hash': typeof MultisigDepositsClaimedHashRoute
  '/multisig-proposal-cancelled/$hash': typeof MultisigProposalCancelledHashRoute
  '/multisig-proposal-created/$hash': typeof MultisigProposalCreatedHashRoute
  '/multisig-proposal-executed/$hash': typeof MultisigProposalExecutedHashRoute
  '/multisig-proposal-ready/$hash': typeof MultisigProposalReadyHashRoute
  '/multisig-proposal-removed/$hash': typeof MultisigProposalRemovedHashRoute
  '/multisig-proposals/$id': typeof MultisigProposalsIdRoute
  '/multisig-signer-approved/$hash': typeof MultisigSignerApprovedHashRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/accounts': typeof AccountsIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/errors': typeof ErrorsIndexRoute
  '/high-security-sets': typeof HighSecuritySetsIndexRoute
  '/miner-leaderboard': typeof MinerLeaderboardIndexRoute
  '/miner-rewards': typeof MinerRewardsIndexRoute
  '/multisig-created': typeof MultisigCreatedIndexRoute
  '/multisig-deposits-claimed': typeof MultisigDepositsClaimedIndexRoute
  '/multisig-proposal-cancelled': typeof MultisigProposalCancelledIndexRoute
  '/multisig-proposal-created': typeof MultisigProposalCreatedIndexRoute
  '/multisig-proposal-executed': typeof MultisigProposalExecutedIndexRoute
  '/multisig-proposal-ready': typeof MultisigProposalReadyIndexRoute
  '/multisig-proposal-removed': typeof MultisigProposalRemovedIndexRoute
  '/multisig-proposals': typeof MultisigProposalsIndexRoute
  '/multisig-signer-approved': typeof MultisigSignerApprovedIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/cancelled-reversible/$txId': typeof TransactionsCancelledReversibleTxIdRoute
  '/transactions/executed-reversible/$txId': typeof TransactionsExecutedReversibleTxIdRoute
  '/transactions/scheduled-reversible/$txId': typeof TransactionsScheduledReversibleTxIdRoute
  '/transactions/wormhole/$id': typeof TransactionsWormholeIdRoute
  '/dev/graphql-benchmark': typeof DevGraphqlBenchmarkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blocks/$id': typeof BlocksIdRoute
  '/errors/$id': typeof ErrorsIdRoute
  '/high-security-sets/$hash': typeof HighSecuritySetsHashRoute
  '/miner-rewards/$hash': typeof MinerRewardsHashRoute
  '/multisig-created/$hash': typeof MultisigCreatedHashRoute
  '/multisig-deposits-claimed/$hash': typeof MultisigDepositsClaimedHashRoute
  '/multisig-proposal-cancelled/$hash': typeof MultisigProposalCancelledHashRoute
  '/multisig-proposal-created/$hash': typeof MultisigProposalCreatedHashRoute
  '/multisig-proposal-executed/$hash': typeof MultisigProposalExecutedHashRoute
  '/multisig-proposal-ready/$hash': typeof MultisigProposalReadyHashRoute
  '/multisig-proposal-removed/$hash': typeof MultisigProposalRemovedHashRoute
  '/multisig-proposals/$id': typeof MultisigProposalsIdRoute
  '/multisig-signer-approved/$hash': typeof MultisigSignerApprovedHashRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/accounts/': typeof AccountsIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/errors/': typeof ErrorsIndexRoute
  '/high-security-sets/': typeof HighSecuritySetsIndexRoute
  '/miner-leaderboard/': typeof MinerLeaderboardIndexRoute
  '/miner-rewards/': typeof MinerRewardsIndexRoute
  '/multisig-created/': typeof MultisigCreatedIndexRoute
  '/multisig-deposits-claimed/': typeof MultisigDepositsClaimedIndexRoute
  '/multisig-proposal-cancelled/': typeof MultisigProposalCancelledIndexRoute
  '/multisig-proposal-created/': typeof MultisigProposalCreatedIndexRoute
  '/multisig-proposal-executed/': typeof MultisigProposalExecutedIndexRoute
  '/multisig-proposal-ready/': typeof MultisigProposalReadyIndexRoute
  '/multisig-proposal-removed/': typeof MultisigProposalRemovedIndexRoute
  '/multisig-proposals/': typeof MultisigProposalsIndexRoute
  '/multisig-signer-approved/': typeof MultisigSignerApprovedIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/cancelled-reversible/$txId': typeof TransactionsCancelledReversibleTxIdRoute
  '/transactions/executed-reversible/$txId': typeof TransactionsExecutedReversibleTxIdRoute
  '/transactions/scheduled-reversible/$txId': typeof TransactionsScheduledReversibleTxIdRoute
  '/transactions/wormhole/$id': typeof TransactionsWormholeIdRoute
  '/dev/graphql-benchmark/': typeof DevGraphqlBenchmarkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$id'
    | '/blocks/$id'
    | '/errors/$id'
    | '/high-security-sets/$hash'
    | '/miner-rewards/$hash'
    | '/multisig-created/$hash'
    | '/multisig-deposits-claimed/$hash'
    | '/multisig-proposal-cancelled/$hash'
    | '/multisig-proposal-created/$hash'
    | '/multisig-proposal-executed/$hash'
    | '/multisig-proposal-ready/$hash'
    | '/multisig-proposal-removed/$hash'
    | '/multisig-proposals/$id'
    | '/multisig-signer-approved/$hash'
    | '/transactions/$hash'
    | '/accounts'
    | '/blocks'
    | '/errors'
    | '/high-security-sets'
    | '/miner-leaderboard'
    | '/miner-rewards'
    | '/multisig-created'
    | '/multisig-deposits-claimed'
    | '/multisig-proposal-cancelled'
    | '/multisig-proposal-created'
    | '/multisig-proposal-executed'
    | '/multisig-proposal-ready'
    | '/multisig-proposal-removed'
    | '/multisig-proposals'
    | '/multisig-signer-approved'
    | '/transactions'
    | '/transactions/cancelled-reversible/$txId'
    | '/transactions/executed-reversible/$txId'
    | '/transactions/scheduled-reversible/$txId'
    | '/transactions/wormhole/$id'
    | '/dev/graphql-benchmark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/$id'
    | '/blocks/$id'
    | '/errors/$id'
    | '/high-security-sets/$hash'
    | '/miner-rewards/$hash'
    | '/multisig-created/$hash'
    | '/multisig-deposits-claimed/$hash'
    | '/multisig-proposal-cancelled/$hash'
    | '/multisig-proposal-created/$hash'
    | '/multisig-proposal-executed/$hash'
    | '/multisig-proposal-ready/$hash'
    | '/multisig-proposal-removed/$hash'
    | '/multisig-proposals/$id'
    | '/multisig-signer-approved/$hash'
    | '/transactions/$hash'
    | '/accounts'
    | '/blocks'
    | '/errors'
    | '/high-security-sets'
    | '/miner-leaderboard'
    | '/miner-rewards'
    | '/multisig-created'
    | '/multisig-deposits-claimed'
    | '/multisig-proposal-cancelled'
    | '/multisig-proposal-created'
    | '/multisig-proposal-executed'
    | '/multisig-proposal-ready'
    | '/multisig-proposal-removed'
    | '/multisig-proposals'
    | '/multisig-signer-approved'
    | '/transactions'
    | '/transactions/cancelled-reversible/$txId'
    | '/transactions/executed-reversible/$txId'
    | '/transactions/scheduled-reversible/$txId'
    | '/transactions/wormhole/$id'
    | '/dev/graphql-benchmark'
  id:
    | '__root__'
    | '/'
    | '/accounts/$id'
    | '/blocks/$id'
    | '/errors/$id'
    | '/high-security-sets/$hash'
    | '/miner-rewards/$hash'
    | '/multisig-created/$hash'
    | '/multisig-deposits-claimed/$hash'
    | '/multisig-proposal-cancelled/$hash'
    | '/multisig-proposal-created/$hash'
    | '/multisig-proposal-executed/$hash'
    | '/multisig-proposal-ready/$hash'
    | '/multisig-proposal-removed/$hash'
    | '/multisig-proposals/$id'
    | '/multisig-signer-approved/$hash'
    | '/transactions/$hash'
    | '/accounts/'
    | '/blocks/'
    | '/errors/'
    | '/high-security-sets/'
    | '/miner-leaderboard/'
    | '/miner-rewards/'
    | '/multisig-created/'
    | '/multisig-deposits-claimed/'
    | '/multisig-proposal-cancelled/'
    | '/multisig-proposal-created/'
    | '/multisig-proposal-executed/'
    | '/multisig-proposal-ready/'
    | '/multisig-proposal-removed/'
    | '/multisig-proposals/'
    | '/multisig-signer-approved/'
    | '/transactions/'
    | '/transactions/cancelled-reversible/$txId'
    | '/transactions/executed-reversible/$txId'
    | '/transactions/scheduled-reversible/$txId'
    | '/transactions/wormhole/$id'
    | '/dev/graphql-benchmark/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsIdRoute: typeof AccountsIdRoute
  BlocksIdRoute: typeof BlocksIdRoute
  ErrorsIdRoute: typeof ErrorsIdRoute
  HighSecuritySetsHashRoute: typeof HighSecuritySetsHashRoute
  MinerRewardsHashRoute: typeof MinerRewardsHashRoute
  MultisigCreatedHashRoute: typeof MultisigCreatedHashRoute
  MultisigDepositsClaimedHashRoute: typeof MultisigDepositsClaimedHashRoute
  MultisigProposalCancelledHashRoute: typeof MultisigProposalCancelledHashRoute
  MultisigProposalCreatedHashRoute: typeof MultisigProposalCreatedHashRoute
  MultisigProposalExecutedHashRoute: typeof MultisigProposalExecutedHashRoute
  MultisigProposalReadyHashRoute: typeof MultisigProposalReadyHashRoute
  MultisigProposalRemovedHashRoute: typeof MultisigProposalRemovedHashRoute
  MultisigProposalsIdRoute: typeof MultisigProposalsIdRoute
  MultisigSignerApprovedHashRoute: typeof MultisigSignerApprovedHashRoute
  TransactionsHashRoute: typeof TransactionsHashRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ErrorsIndexRoute: typeof ErrorsIndexRoute
  HighSecuritySetsIndexRoute: typeof HighSecuritySetsIndexRoute
  MinerLeaderboardIndexRoute: typeof MinerLeaderboardIndexRoute
  MinerRewardsIndexRoute: typeof MinerRewardsIndexRoute
  MultisigCreatedIndexRoute: typeof MultisigCreatedIndexRoute
  MultisigDepositsClaimedIndexRoute: typeof MultisigDepositsClaimedIndexRoute
  MultisigProposalCancelledIndexRoute: typeof MultisigProposalCancelledIndexRoute
  MultisigProposalCreatedIndexRoute: typeof MultisigProposalCreatedIndexRoute
  MultisigProposalExecutedIndexRoute: typeof MultisigProposalExecutedIndexRoute
  MultisigProposalReadyIndexRoute: typeof MultisigProposalReadyIndexRoute
  MultisigProposalRemovedIndexRoute: typeof MultisigProposalRemovedIndexRoute
  MultisigProposalsIndexRoute: typeof MultisigProposalsIndexRoute
  MultisigSignerApprovedIndexRoute: typeof MultisigSignerApprovedIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsCancelledReversibleTxIdRoute: typeof TransactionsCancelledReversibleTxIdRoute
  TransactionsExecutedReversibleTxIdRoute: typeof TransactionsExecutedReversibleTxIdRoute
  TransactionsScheduledReversibleTxIdRoute: typeof TransactionsScheduledReversibleTxIdRoute
  TransactionsWormholeIdRoute: typeof TransactionsWormholeIdRoute
  DevGraphqlBenchmarkIndexRoute: typeof DevGraphqlBenchmarkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-signer-approved/': {
      id: '/multisig-signer-approved/'
      path: '/multisig-signer-approved'
      fullPath: '/multisig-signer-approved'
      preLoaderRoute: typeof MultisigSignerApprovedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposals/': {
      id: '/multisig-proposals/'
      path: '/multisig-proposals'
      fullPath: '/multisig-proposals'
      preLoaderRoute: typeof MultisigProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-removed/': {
      id: '/multisig-proposal-removed/'
      path: '/multisig-proposal-removed'
      fullPath: '/multisig-proposal-removed'
      preLoaderRoute: typeof MultisigProposalRemovedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-ready/': {
      id: '/multisig-proposal-ready/'
      path: '/multisig-proposal-ready'
      fullPath: '/multisig-proposal-ready'
      preLoaderRoute: typeof MultisigProposalReadyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-executed/': {
      id: '/multisig-proposal-executed/'
      path: '/multisig-proposal-executed'
      fullPath: '/multisig-proposal-executed'
      preLoaderRoute: typeof MultisigProposalExecutedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-created/': {
      id: '/multisig-proposal-created/'
      path: '/multisig-proposal-created'
      fullPath: '/multisig-proposal-created'
      preLoaderRoute: typeof MultisigProposalCreatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-cancelled/': {
      id: '/multisig-proposal-cancelled/'
      path: '/multisig-proposal-cancelled'
      fullPath: '/multisig-proposal-cancelled'
      preLoaderRoute: typeof MultisigProposalCancelledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-deposits-claimed/': {
      id: '/multisig-deposits-claimed/'
      path: '/multisig-deposits-claimed'
      fullPath: '/multisig-deposits-claimed'
      preLoaderRoute: typeof MultisigDepositsClaimedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-created/': {
      id: '/multisig-created/'
      path: '/multisig-created'
      fullPath: '/multisig-created'
      preLoaderRoute: typeof MultisigCreatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miner-rewards/': {
      id: '/miner-rewards/'
      path: '/miner-rewards'
      fullPath: '/miner-rewards'
      preLoaderRoute: typeof MinerRewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miner-leaderboard/': {
      id: '/miner-leaderboard/'
      path: '/miner-leaderboard'
      fullPath: '/miner-leaderboard'
      preLoaderRoute: typeof MinerLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-security-sets/': {
      id: '/high-security-sets/'
      path: '/high-security-sets'
      fullPath: '/high-security-sets'
      preLoaderRoute: typeof HighSecuritySetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/': {
      id: '/errors/'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$hash': {
      id: '/transactions/$hash'
      path: '/transactions/$hash'
      fullPath: '/transactions/$hash'
      preLoaderRoute: typeof TransactionsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-signer-approved/$hash': {
      id: '/multisig-signer-approved/$hash'
      path: '/multisig-signer-approved/$hash'
      fullPath: '/multisig-signer-approved/$hash'
      preLoaderRoute: typeof MultisigSignerApprovedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposals/$id': {
      id: '/multisig-proposals/$id'
      path: '/multisig-proposals/$id'
      fullPath: '/multisig-proposals/$id'
      preLoaderRoute: typeof MultisigProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-removed/$hash': {
      id: '/multisig-proposal-removed/$hash'
      path: '/multisig-proposal-removed/$hash'
      fullPath: '/multisig-proposal-removed/$hash'
      preLoaderRoute: typeof MultisigProposalRemovedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-ready/$hash': {
      id: '/multisig-proposal-ready/$hash'
      path: '/multisig-proposal-ready/$hash'
      fullPath: '/multisig-proposal-ready/$hash'
      preLoaderRoute: typeof MultisigProposalReadyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-executed/$hash': {
      id: '/multisig-proposal-executed/$hash'
      path: '/multisig-proposal-executed/$hash'
      fullPath: '/multisig-proposal-executed/$hash'
      preLoaderRoute: typeof MultisigProposalExecutedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-created/$hash': {
      id: '/multisig-proposal-created/$hash'
      path: '/multisig-proposal-created/$hash'
      fullPath: '/multisig-proposal-created/$hash'
      preLoaderRoute: typeof MultisigProposalCreatedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-proposal-cancelled/$hash': {
      id: '/multisig-proposal-cancelled/$hash'
      path: '/multisig-proposal-cancelled/$hash'
      fullPath: '/multisig-proposal-cancelled/$hash'
      preLoaderRoute: typeof MultisigProposalCancelledHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-deposits-claimed/$hash': {
      id: '/multisig-deposits-claimed/$hash'
      path: '/multisig-deposits-claimed/$hash'
      fullPath: '/multisig-deposits-claimed/$hash'
      preLoaderRoute: typeof MultisigDepositsClaimedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig-created/$hash': {
      id: '/multisig-created/$hash'
      path: '/multisig-created/$hash'
      fullPath: '/multisig-created/$hash'
      preLoaderRoute: typeof MultisigCreatedHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miner-rewards/$hash': {
      id: '/miner-rewards/$hash'
      path: '/miner-rewards/$hash'
      fullPath: '/miner-rewards/$hash'
      preLoaderRoute: typeof MinerRewardsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-security-sets/$hash': {
      id: '/high-security-sets/$hash'
      path: '/high-security-sets/$hash'
      fullPath: '/high-security-sets/$hash'
      preLoaderRoute: typeof HighSecuritySetsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/$id': {
      id: '/errors/$id'
      path: '/errors/$id'
      fullPath: '/errors/$id'
      preLoaderRoute: typeof ErrorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$id': {
      id: '/blocks/$id'
      path: '/blocks/$id'
      fullPath: '/blocks/$id'
      preLoaderRoute: typeof BlocksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/graphql-benchmark/': {
      id: '/dev/graphql-benchmark/'
      path: '/dev/graphql-benchmark'
      fullPath: '/dev/graphql-benchmark'
      preLoaderRoute: typeof DevGraphqlBenchmarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/wormhole/$id': {
      id: '/transactions/wormhole/$id'
      path: '/transactions/wormhole/$id'
      fullPath: '/transactions/wormhole/$id'
      preLoaderRoute: typeof TransactionsWormholeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/scheduled-reversible/$txId': {
      id: '/transactions/scheduled-reversible/$txId'
      path: '/transactions/scheduled-reversible/$txId'
      fullPath: '/transactions/scheduled-reversible/$txId'
      preLoaderRoute: typeof TransactionsScheduledReversibleTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/executed-reversible/$txId': {
      id: '/transactions/executed-reversible/$txId'
      path: '/transactions/executed-reversible/$txId'
      fullPath: '/transactions/executed-reversible/$txId'
      preLoaderRoute: typeof TransactionsExecutedReversibleTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/cancelled-reversible/$txId': {
      id: '/transactions/cancelled-reversible/$txId'
      path: '/transactions/cancelled-reversible/$txId'
      fullPath: '/transactions/cancelled-reversible/$txId'
      preLoaderRoute: typeof TransactionsCancelledReversibleTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsIdRoute: AccountsIdRoute,
  BlocksIdRoute: BlocksIdRoute,
  ErrorsIdRoute: ErrorsIdRoute,
  HighSecuritySetsHashRoute: HighSecuritySetsHashRoute,
  MinerRewardsHashRoute: MinerRewardsHashRoute,
  MultisigCreatedHashRoute: MultisigCreatedHashRoute,
  MultisigDepositsClaimedHashRoute: MultisigDepositsClaimedHashRoute,
  MultisigProposalCancelledHashRoute: MultisigProposalCancelledHashRoute,
  MultisigProposalCreatedHashRoute: MultisigProposalCreatedHashRoute,
  MultisigProposalExecutedHashRoute: MultisigProposalExecutedHashRoute,
  MultisigProposalReadyHashRoute: MultisigProposalReadyHashRoute,
  MultisigProposalRemovedHashRoute: MultisigProposalRemovedHashRoute,
  MultisigProposalsIdRoute: MultisigProposalsIdRoute,
  MultisigSignerApprovedHashRoute: MultisigSignerApprovedHashRoute,
  TransactionsHashRoute: TransactionsHashRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ErrorsIndexRoute: ErrorsIndexRoute,
  HighSecuritySetsIndexRoute: HighSecuritySetsIndexRoute,
  MinerLeaderboardIndexRoute: MinerLeaderboardIndexRoute,
  MinerRewardsIndexRoute: MinerRewardsIndexRoute,
  MultisigCreatedIndexRoute: MultisigCreatedIndexRoute,
  MultisigDepositsClaimedIndexRoute: MultisigDepositsClaimedIndexRoute,
  MultisigProposalCancelledIndexRoute: MultisigProposalCancelledIndexRoute,
  MultisigProposalCreatedIndexRoute: MultisigProposalCreatedIndexRoute,
  MultisigProposalExecutedIndexRoute: MultisigProposalExecutedIndexRoute,
  MultisigProposalReadyIndexRoute: MultisigProposalReadyIndexRoute,
  MultisigProposalRemovedIndexRoute: MultisigProposalRemovedIndexRoute,
  MultisigProposalsIndexRoute: MultisigProposalsIndexRoute,
  MultisigSignerApprovedIndexRoute: MultisigSignerApprovedIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsCancelledReversibleTxIdRoute:
    TransactionsCancelledReversibleTxIdRoute,
  TransactionsExecutedReversibleTxIdRoute:
    TransactionsExecutedReversibleTxIdRoute,
  TransactionsScheduledReversibleTxIdRoute:
    TransactionsScheduledReversibleTxIdRoute,
  TransactionsWormholeIdRoute: TransactionsWormholeIdRoute,
  DevGraphqlBenchmarkIndexRoute: DevGraphqlBenchmarkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
